server:
  port: 9901
logging:
  path: logs
  file: mylog.log

spring:
   application:
          name: myTest
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test1224?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
       username: root
       password:

mybatis:
  type-aliases-package: com.course.model   #(用来做映射)
  mapper-locations:
       - mapper/*  #（用来映射mysql.xml文件）


